#!/bin/bash 

## this app is based on one by tenner that can be downloaded at http://tenr.de/snippets/scripts/shot.sh
## it has been modified and expanded for use with MX-Fluxbox
## released under GPLv3

#set up translation

source gettext.sh

export TEXTDOMAIN=mxfb-accessories
export TEXTDOMAINDIR="/usr/share/locale"

## the following parameters are set in ${HOME}/.config/MX-Linux/mxfb-quickshot.conf
#OPTION
#DESTDIR=""
#NAME=""
#TIMEOUT=""
#SUF=""
#PRE=""
#ICONPATH=""
#SHOWHELP=""
#SHOWSUCCESS=""

if [ ! -f "$HOME/.config/MX-Linux/mxfb-quickshot.conf" ]; then 
cp /usr/share/mxfb-quickshot/mxfb-quickshot.conf $HOME/.config/MX-Linux/mxfb-quickshot.conf; 
fi

[ -r "$HOME/.config/user-dirs.dirs" ] && source "$HOME/.config/user-dirs.dirs"
source ${HOME}/.config/MX-Linux/mxfb-quickshot.conf

if [ ! -f $HOME/.restore/MX-Linux/mxfb-quickshot.conf* ]; then
MESSAGE="$(eval_gettext 'This upgrade will install a new config file \n\nThe existing file will be backed up as \n\n<b>$HOME/.restore/MX-Linux/mxfb-quickshot.conf_$NOW</b>')"

##begin message box
yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=350 --height=200 --text-align=center --text="\n\n$MESSAGE\n\n" --text-align=center --center --borders=20 --button="gtk-cancel":7 --button="$(gettext 'OK to proceed?')":6

if [ ! "$?" = "6" ]; then
exit 0
		
else

mkdir -p $HOME/.restore/MX-Linux/
cp $HOME/.config/MX-Linux/mxfb-quickshot.conf $HOME/.restore/MX-Linux/mxfb-quickshot.conf_$(date -d "today" +"%Y%m%d")

fi
fi

if [ $SHOWHELP = "yes" ]; then
notify-send -i $ICONPATH -t 9000 "
$(eval_gettext '
(Click anywhere inside this window to capture it)


MODES

	A window: press Print and click anywhere inside
		Actuve window: Press ALT + PRINT

	Selection: press Print and draw a rectangle

	Desktop: press Print and click the background 			
		OR: press SHIFT + PRINT
    

PREFERENCES

	$HOME/.config/MX-Linux/mxfb-quickshot.conf

		Hide this message: SHOWHELP="no"

		Hide Success message: SHOWSUCCES="no"')"
     
fi

display_help() {
	cat << EOF
	Usage: `basename "$0"` [-r/r/-w/w/-b/b/-u/u] [-png|png|-jpg|jpg]
EOF
}

take_shot() {
	scrot ${OPTION} "${PRE}${NAME}.${SUF}" -e 'mv $f '$DESTDIR''

if [ "$?" = "1" ]; then
notify-send -i $ICONPATH -t 3000 "
	$(gettext 'Cancelled!')"
exit 0
fi

if [ $? -eq 2 ] ; then
    echo "$(gettext 'exiting, no image selected')"
    exit 1
fi
}

if [ $# -gt 2 ]
then
	display_help
	exit 1
elif [ $# -eq 0 ]
then
	take_shot
   
if [ $SHOWSUCCESS = "yes" ] ; then	
	notify-send -i $ICONPATH -t 3000 "
	$(gettext 'Success!')"
fi
exit 0
else
	case "$1" in
		-r|r|-R|R|root|Root|-root|-Root)
			OPTION=""
			;;		
		-u|u|-U|U|focused|Focused|-focused|-Focused)
			OPTION="-u"
			;;
		*)
			display_help
			exit 1
	esac

	case "$2" in
		jpg|JPG|-jpg|-JPG)
			SUF="jpg"
			;;	
		png|PNG|-png|-PNG)
			SUF="png"
			;;
		*)
			display_help
			exit 1
	esac
	take_shot
	exit 0
fi
