#!/bin/bash

## this app is based on one by tenner that can be downloaded at http://tenr.de/snippets/scripts/shot.sh
## it has been modified and expanded for use with MX-Fluxbox
## released under GPLv3

#set up translation

# mxfb-quickshot version
VERSION="230201"

export TEXTDOMAIN=mxfb-accessories
export TEXTDOMAINDIR="/usr/share/locale"
source gettext.sh

[ -r "$HOME/.config/user-dirs.dirs" ] && source "$HOME/.config/user-dirs.dirs"

## the following parameters are set in ${HOME}/.config/MX-Linux/mxfb-quickshot.conf
#OPTION
#DESTDIR=""
#NAME=""
#TIMEOUT=""
#SUF=""
#PRE=""
#ICONPATH=""
#SHOWHELP=""
#SHOWSUCCESS=""


BASE_NAME=$(basename "$0")

DATE=$(date '+%Y%m%d')
CONFIG_DIR="$HOME/.config/MX-Linux"
BACKUP_DIR="$HOME/.restore/MX-Linux"

CONFIG_NAME="mxfb-quickshot.conf"
BACKUP_NAME="${CONFIG_NAME}_${VERSION}_${DATE}"
FLUXBOXKEYS='$HOME'/.fluxbox/keys
USER_CONFIG='$HOME'/.config/MX-Linux/${CONFIG_NAME}

BACKUP_CONF="${BACKUP_DIR}/${BACKUP_NAME}"
SYSTEM_CONF="/usr/share/mxfb-quickshot/mxfb-quickshot.conf"


# messages shown

NONE_SELECTED=$(gettext 'exiting, no image selected')
    CANCELLED="$(gettext 'Cancelled!')"
      SUCCESS="    $(gettext 'Success!')"
#USAGE="Usage: $BASE_NAME [-r/r/-w/w/-b/b/-u/u] [-png|png|-jpg|jpg]"

UPGRADE_MESSAGE=$(gettext 'This will install a new config file')
BACKUP_MESSAGE=$(gettext 'The existing file will be backed up as:')
MESSAGE="$UPGRADE_MESSAGE\n\n$BACKUP_MESSAGE\n\n<b>$BACKUP_CONF</b>"

USER_CONFIG="${CONFIG_DIR}/${CONFIG_NAME}"
HELP_MESSAGE=$(eval_gettext '

How to capture

    --WINDOW: press Print, then click anywhere inside

    --DESKTOP: press Print, then click the background

    --SELECTION: press Print, then draw a rectangle
    
    ')
HELP_HINTS=$(eval_gettext '
Hints 

	--The Help screen will only show once 

	--Capture by clicking on it after windows close 

	--$USER_CONFIG')
ICONPATH="/usr/share/icons/Papirus/24x24/devices/camera.svg"
if [ -z "$ICONPATH" ] || [ ! -e "$ICONPATH" ]; then
   # take icon from theme  
   ICONPATH=camera-photo
fi

if [ ! -f ${BACKUP_DIR}/${CONFIG_NAME}* ]; then
/usr/bin/notify-send -i "$ICONPATH" -t 30000 "$HELP_MESSAGE" 

sleep 3
YAD=(yad
    --title="Quickshot"
    --class="$CLASS"
    --window-icon="$ICONPATH"
    --height=300
    --width=300
    --fixed
    --text-align=left
    --text="\n\n<b>$HELP_HINTS</b>\n\n"
    --center
    --borders=20
    --button=gtk-ok
    )
      
       "${YAD[@]}"
	
fi

if ! ls "${BACKUP_DIR}/${CONFIG_NAME}_${VERSION}"* >/dev/null 2>&1 &&
   [ -r "$USER_CONFIG" ] &&
   [ -r "$SYSTEM_CONF" ]; then

   YAD=(yad
    --title="Quickshot"
    --class="$CLASS"
    --window-icon="$ICONPATH"
    --width=350
    --height=200
    --text-align=center
    --text="\n\n$MESSAGE\n\n"
    --center
    --borders=20
    --button="gtk-cancel":7
    --button="$(gettext 'OK to proceed?')":6
    )

   "${YAD[@]}"
   [ ! "$?" = "6" ] && exit 0

   [ -d "$BACKUP_DIR" ] || mkdir -p "$BACKUP_DIR"
   cp "$USER_CONFIG" "$BACKUP_CONF"
   cp "$SYSTEM_CONF" "$USER_CONFIG"
   
fi

if [ -r "$SYSTEM_CONF" ] && [ ! -r "$USER_CONFIG" ]; then
      [ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"
      cp "$SYSTEM_CONF" "$USER_CONFIG"
fi
[ -r "$USER_CONFIG" ] &&  source "$USER_CONFIG"

# user config sanity check 
# set to reasonable vaules with := assignment only if not set already

: ${OPTION:="-s -q 100"} 
: ${NAME:=$(date +%y%m%d_%H%M%S)}
: ${TIMEOUT:=5}
: ${SUF:=png}
: ${SHOWHELP:=yes}
: ${PRE:=quickshot_}


# use current dir if destdir is not defined
: ${DESTDIR:=.}

display_help() {
    printf "%s\n" "$USAGE"

take_shot() {
    local ret
    local filename="${PRE}${NAME}.${SUF}"
    local exec_option='mv $f '"$DESTDIR"
    if [ "$(readlink -e "$DESTDIR")" = "$(readlink -e "$PWD")" ]; then
       scrot ${OPTION} "${PRE}${NAME}.${SUF}"
       ret=$?
    else
       scrot ${OPTION} "${PRE}${NAME}.${SUF}" -e "$exec_option"
       ret=$?
    fi
    
    if [ $ret = 1 ]; then
       notify-send -i "$ICONPATH" -t 3000 "$CANCELLED"
       exit 0
    fi

    if [ $ret = 2 ] ; then
       echo "$NONE_SELECTED"
       exit 1
    fi
    return $ret
}

if [ $# -gt 2 ]; then
   display_help
   exit 1
fi

if [ $# -eq 0 ]; then
   take_shot &&  notify-send -i $ICONPATH -t 3000 "$SUCCESS"
   exit 0
fi
}

case "$1" in
    -r|r|-R|R|root|Root|-root|-Root)
        OPTION=""
        ;;
    -u|u|-U|U|focused|Focused|-focused|-Focused)
        OPTION="-u"
        ;;
    *)
        display_help
        exit 1
        ;;
esac

case "$2" in
    jpg|JPG|-jpg|-JPG)
        SUF="jpg"
        ;;
    png|PNG|-png|-PNG)
        SUF="png"
        ;;
    *)
        display_help
        exit 1
        ;;
esac
take_shot 

exit $?
